# Site settings
title: Carsten's R blog
email: carsten.behring@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog on R, data science and open data.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://behrica.github.com/" # the base hostname & protocol for your site

github_username:  behrica
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
