---
layout: post
title: Topics from EFSA opinions with word2vec
date: "`r Sys.time()`"
published: true
tags: [word2vec]


liftr:
  from: rocker/hadleyverse
  pandoc: false
  
    
  maintainer: Carsten Behring
  maintainer_email: carsten.behring@gmail.com
---

```{r}
library(wordVectors)

wv <- wordVectors::read.vectors("efsa_ops.vectors")
nearest_to(wv,wv[['germany']])

```

```{r}
library(networkD3)
library(dplyr)

networkData <- tbl_df(read.csv("edges.csv",stringsAsFactors=F)) %>%
    select(source,target,group,value)





nodeIDs <- unique(c(networkData$target,networkData$source))
sources <- c(networkData$source)
targets  <- c(networkData$target)

links <-  data.frame(source=sources,target=targets,value=networkData$value)
links$source <-  sapply(links$source,function(x) {which(nodeIDs == x)-1})
links$target <-  sapply(links$target,function(x) {which(nodeIDs == x)-1})


findGroup <- function(x) {
    index <- which(nodeIDs == x)
    
    networkData$source[ifelse(index %in% links$target,which(links$target==index),which(links$source==index))]
}

groups=unname(sapply(nodeIDs, findGroup))
nodes <- data.frame(name=c(networkData$target,networkData$source),
                    group=c(networkData$source,networkData$source)) %>%
    distinct(name)
                    
nodes$group=groups



network = forceNetwork(Links = links, Nodes = nodes, Source = "source",
                       Target = "target", Value = "value", NodeID = "name",
                       Group = "group", 
                       zoom = TRUE,linkWidth=c(1),
                       legend=TRUE,fontSize = 10,opacity = 0.6,
                       linkDistance =
                           JS("function(d){return d.value * 10}"),
                       opacityNoHover = 0
                       )
network

```

